version: "3.9"

services:
  redis:
      image: redis
      volumes:
        - ./redisdata:/data
        - dev-static-data:/vol/web

  app:
    build:
      context: .
      args:
      - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - redis


  celery:
      restart: always
      build:
        context: .
      command: celery -A app worker -l info 
      volumes:
        - ./app:/app
        - dev-static-data:/vol/web      
      depends_on:
        # - db
        - redis
        - app

  worker_channels:
    build:
      context: .
      args:
        - DEV=true
    command: python manage.py runworker websocket
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    depends_on:
      - redis

  
  channels:
    build:
      context: .
      args:
        - DEV=true
    command: daphne -b 0.0.0.0 -p 8001 app.asgi:application
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    expose:
      - 8001
    depends_on:
      - redis



volumes:
  dev-db-data:
  redisdata:
  dev-static-data:
