# Generated by Django 3.2.25 on 2024-03-17 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ip',
            field=models.CharField(blank=True, help_text='Enter a valid IP address.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$')]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient_contact',
            field=models.CharField(blank=True, help_text='Enter a valid 10-digit phone number.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='physician_contact',
            field=models.CharField(blank=True, help_text='Enter a valid 10-digit phone number.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
